### ISSUE TITLE
Any plan for a Cran release

### ISSUE THREAD

**Issue by pommedeterresautee** [bnosac/GAlogger#2]
Releasing on Cran would help to deploy this lib more easily in Prod

**Comment by jwijffels** [comment]
No. I don't think CRAN compliance would allow such a package. I'm not going to bother CRAN with this. I tested R CMD check on win-builder with the current examples in the package, it showed me where the CRAN machines were hosted and in principle anyone who makes use of the package can send data to Google servers. I don't think collecting that information is ok for CRAN.
You can just install from http://www.datatailor.be/rcube. Which is our local machine.

```
install.packages("uuid")
install.packages("curl")
install.packages("GAlogger", repos = "http://www.datatailor.be/rcube", type = "source")
```

**Comment by pommedeterresautee** [comment]
Ok I understand. I close
