### ISSUE TITLE
Client ID not picks up by GA

### ISSUE THREAD

**Issue by dylancis** [bnosac/GAlogger#3]
Thank you very much for your package. I have an issue wit the `CLIENT_ID` which does not get pick up bu Google Analytics. I am using:
` ga_set_user_id(user_id = session$userData$app.login.name)
`
But GA still shows:
![image](https://user-images.githubusercontent.com/4976433/47757267-883f4e00-dc73-11e8-9054-d9222ed6e714.png)

Do you know why?

**Comment by jwijffels** [comment]
Client id is different then user id. Did you set GALOG_UA_CLIENTID before you loaded the package
